from pydantic_settings import BaseSettings, SettingsConfigDict
from typing import Optional

class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="ignore")

    SECRET_KEY: str = "changeme-in-production-use-long-random-string"
    ALGORITHM: str = "HS256"
    ACCESS_TOKEN_EXPIRE_DAYS: int = 7
    DATABASE_URL: str = "sqlite:///./sports_analytics.db"
    STRIPE_SECRET_KEY: str = ""
    STRIPE_PRICE_ID_MONTHLY: str = ""
    STRIPE_PRICE_ID_YEARLY: str = ""
    STRIPE_WEBHOOK_SECRET: str = ""
    FRONTEND_URL: str = "http://localhost:5173"
    TRIAL_DAYS: int = 30
    # Admin API (app/routers/admin.py) -- a single shared secret rather than
    # an is_admin column, since there's one admin (whoever runs this app) and
    # a header key checked before touching the DB is simpler than a whole
    # permission system for an audience of one. Blank means the admin routes
    # refuse everything -- fails closed on a fresh deploy that hasn't set it,
    # rather than leaving user data open by default.
    ADMIN_API_KEY: str = ""
    # Outbound email (app/notifications.py) -- currently just the "you got a
    # new signup" ping. Plain SMTP, not a provider SDK, so switching
    # providers later is new env vars, not new code: most transactional
    # email services (Resend, SendGrid, Postmark, ...) expose an SMTP relay
    # too. Defaults point at Gmail so the fastest path to working is an
    # existing Gmail address + an App Password (Google Account -> Security
    # -> 2-Step Verification -> App Passwords), not signing up for a new
    # service. Blank SMTP_USER/PASSWORD or ADMIN_NOTIFY_EMAIL just means
    # "notifications off" -- registration itself never depends on this.
    SMTP_HOST: str = "smtp.gmail.com"
    SMTP_PORT: int = 587
    SMTP_USER: str = ""
    SMTP_PASSWORD: str = ""
    SMTP_FROM: str = ""             # blank -> falls back to SMTP_USER
    ADMIN_NOTIFY_EMAIL: str = ""    # where new-user pings go; blank = off
    NBA_STATS_URL: str = "https://github.com/mtdewrocks/sports_analysis/raw/main/data/NBA_Player_Stats.parquet"
    NFL_STATS_URL: str = "https://github.com/mtdewrocks/sports_analysis/raw/main/data/Player_Stats_Weekly.parquet"
    NFL_TEAM_STATS_URL: str = "https://github.com/mtdewrocks/sports_analysis/raw/main/data/2025_Team_Stats.xlsx"
    NBA_PROPS_URL: str = "https://github.com/mtdewrocks/sports_analysis/raw/main/data/Basketball_Props.xlsx"
    # Now generated by update_props.yml, so it lives in the release like every
    # other pipeline output. Parquet rather than xlsx: nobody hand-edits it any
    # more, and openpyxl is the slowest reader in the app.
    MLB_PROPS_URL: str = "https://github.com/mtdewrocks/sports-analytics/releases/download/data-mlb/Daily_Props.parquet"
    NFL_PROPS_URL: str = "https://github.com/mtdewrocks/sports-analytics/releases/download/data-nfl/NFL_Props.parquet"
    # Release assets rather than files on `main`. Same URL SHAPE -- loader.py
    # builds every path as f"{base}/{filename}" and needs no change -- but the
    # bytes now come out of a GitHub Release instead of git history, so an
    # hourly data refresh no longer writes a commit, no longer grows the repo,
    # and no longer triggers a Render redeploy.
    #
    # Release assets are a FLAT namespace per tag: there are no subdirectories,
    # so filenames must be unique within a tag. That is why MLB and NFL get
    # separate tags rather than one shared one.
    #
    # Pitcher headshots deliberately stay on `main` -- they are append-only,
    # cause no history churn, and the frontend links them as a directory
    # (MLBMatchup.tsx IMAGE_BASE), which a flat asset namespace cannot serve.
    MLB_BASE_URL: str = "https://github.com/mtdewrocks/sports-analytics/releases/download/data-mlb"
    NFL_BASE_URL: str = "https://github.com/mtdewrocks/sports-analytics/releases/download/data-nfl"

settings = Settings()

# SQLAlchemy requires "postgresql://" but Render provides "postgres://"
# Auto-fix this common gotcha so it works regardless of what Render gives us
if settings.DATABASE_URL.startswith("postgres://"):
    settings.DATABASE_URL = settings.DATABASE_URL.replace("postgres://", "postgresql://", 1)
